RT/RT.SSE.Lotto/Models/ErrorViewModel.cs
using System;

namespace RT.SSE.Lotto.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RT/RT.SSE.Lotto/Models/LottoDrawMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RT.SSE.Lotto.Models
{
    public class LottoDrawMessage
    {
        public DateTime DrawTimestamp { get; set; }
        public int Nr1 { get; set; }
        public int Nr2 { get; set; }
        public int Nr3 { get; set; }
        public int Nr4 { get; set; }
        public int Nr5 { get; set; }
        public int Nr6 { get; set; }
    }
}

RT/RT.SSE.Lotto/Controllers/LottoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RT.SSE.Lotto.Models;

namespace RT.SSE.Lotto.Controllers
{
    public class LottoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task StartDrawing()
        {
            Response.Headers.Add("Content-Type", "text/event-stream");
            var rand = new Random();
            while (true)
            {
                var drawMessage = new LottoDrawMessage()
                {
                    DrawTimestamp = DateTime.Now,
                    Nr1 = rand.Next(1, 45),
                    Nr2 = rand.Next(1, 45),
                    Nr3 = rand.Next(1, 45),
                    Nr4 = rand.Next(1, 45),
                    Nr5 = rand.Next(1, 45),
                    Nr6 = rand.Next(1, 45)
                };
                string jsonMessageObj = Newtonsoft.Json.JsonConvert.SerializeObject(drawMessage); // serialization to json.
                var messageTemplate = $"data: {jsonMessageObj} \n\n"; // message template. Critical for SSE functioning.
                var messageBytes = Encoding.ASCII.GetBytes(messageTemplate);
                await Response.Body.WriteAsync(messageBytes, 0, messageBytes.Length);
                await Response.Body.FlushAsync();
                await Task.Delay(TimeSpan.FromSeconds(5));
            }
        }
    }
}

RT/RT.SSE.Lotto/Views/Lotto/Index.cshtml
@{
    ViewData["Title"] = "LOTTO - lucky numbers";
}
<div class="row lottery-container">
    <div class="col-lg-12 ">
        <span>Lucky lottery numbers:</span>
        <ul id="lucky-numbers">
        </ul>
    </div>
</div>

RT/RT.SSE.Lotto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RT.SSE.Lotto</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Lotto" asp-action="Index" class="navbar-brand">RT.SSE.Lotto</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - RT.SSE.Lotto</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>